print('\033[7;37m########## Exercícios de Pyhton ##########\033[m')
print('\033[7;37m##########    Exercício  004    ##########\033[m')
qualquer = input('Defina  um valor para a variável \'qualquer\'\n')
print('\033[0;31mO tipo da variavel \'qualquer\' é {}\033[m'.format(type(qualquer)))
print('\033[0;32mA variável \'qualquer\' é alfanumerica? {}\033[m'.format(qualquer.isalnum()))
print('\033[0;33mA variável \'qualquer\' é um número? {}\033[m'.format(qualquer.isnumeric()))
print('\033[0;34mA variável \'qualquer\' é um número decimal? {}\033[m'.format(qualquer.isdecimal()))
print('\033[0;35mA variável \'qualquer\' é um número? {}\033[m'.format(qualquer.islower()))
print('\033[0;36mA variável \'qualquer\' é composta somente por espaços? {}\033[m'.format(qualquer.isspace()))
print('\033[0;37mA variável \'qualquer\' é imprimível? {}\033[m'.format(qualquer.isprintable()))
print('\033[0;31mA variável \'qualquer\' é um indentificador? {}\033[m'.format(qualquer.isidentifier()))
print('\033[0;32mA variável \'qualquer\' está em maiúsculas? {}\033[m'.format(qualquer.isupper()))
print('\033[0;33mA variável \'qualquer\' está em minúsculas? {}\033[m'.format(qualquer.islower()))
print('\033[0;34mA variável \'qualquer\' está capitalizada? {}\033[m'.format(qualquer.istitle()))
print('\033[7;37m##########################################\033[m')
print('\033[7;37m##########################################\033[m')
