print('########## Exercícios de Pyhton ##########')
print('##########    Exercício  004    ##########')
qualquer = input('Defina  um valor para a variável \'qualquer\'\n')
print('O tipo da variavel \'qualquer\' é {}'.format(type(qualquer)))
print('A variável \'qualquer\' é alfanumerica? {}'.format(qualquer.isalnum()))
print('A variável \'qualquer\' é um número? {}'.format(qualquer.isnumeric()))
print('A variável \'qualquer\' é um número decimal? {}'.format(qualquer.isdecimal()))
print('A variável \'qualquer\' é um número? {}'.format(qualquer.islower()))
print('A variável \'qualquer\' é composta somente por espaços? {}'.format(qualquer.isspace()))
print('A variável \'qualquer\' é imprimível? {}'.format(qualquer.isprintable()))
print('A variável \'qualquer\' é um indentificador? {}'.format(qualquer.isidentifier()))
print('##########################################')
print('##########################################')
