print('########## Exercícios de Python ##########')
print('##########    Exercício  005    ##########')
mainNumber = int(input('Digite um número qualquer: '))
print('O antecessor do número {} é {} e o sucessor é {}'.format(mainNumber, mainNumber - 1, mainNumber + 1))
print('##########################################')
print('##########################################')
