print('########## Exercícios de Python ##########')
print('##########    Exercício  009    ##########')
numero = int(input('Digite um número inteiro de 0 a 9 para verificar sua tabuada: \n'))
print('#' * 42)
print('{} x {} = {}'.format(numero, '1', (numero * 1)))
print('{} x {} = {}'.format(numero, '2', (numero * 1)))
print('{} x {} = {}'.format(numero, '3', (numero * 1)))
print('{} x {} = {}'.format(numero, '4', (numero * 1)))
print('{} x {} = {}'.format(numero, '5', (numero * 1)))
print('{} x {} = {}'.format(numero, '6', (numero * 1)))
print('{} x {} = {}'.format(numero, '7', (numero * 1)))
print('{} x {} = {}'.format(numero, '8', (numero * 1)))
print('{} x {} = {}'.format(numero, '9', (numero * 1)))
print('{} x {} = {}'.format(numero, '10', (numero * 1)))
print('#' * 42)
