print('########## Exercícios de Pyhton ##########')
print('##########    Exercício  003    ##########')
num = int(input('Digite um número qualquer \n'))
num2 = int(input('Digite outro nuúmero \n'))
print('A soma entre {} e {} é {}'.format(num, num2, (num + num2)))
print('##########################################')
print('##########################################')
