print('#' * 42)
print('#' * 15, 'Exercício 015', '#' * 15)

frase = '      Curso em video Python    '
print(len(frase))
print(frase.count('o'))
print(frase.count('o', 0, 15))
print(frase.find('v'))
print('em' in frase)
print(frase.replace('Python', 'Python III'))
print(frase)
print(frase.upper())
print(frase.capitalize())
print(frase.strip())
print(frase.rstrip())
print(len(frase.rstrip()))
print(frase.lstrip())
print(len(frase.lstrip()))
word1 = frase.split()
print(word1[0])
print(word1[1])
print(word1[2])
print(word1[3])
print(word1)
print("""Olá! Estou printando um texto grande aqui, vamos ver se funciona
         Será que vai? """)

print('#' * 42)
