print('\033[7m########## Exercícios de Python ##########\033[m')
print('\033[7m##########    Exercício  007    ##########\033[m')
nota1 = float(input('Digite a primeira nota do aluno: '))
nota2 = float(input('Digite a segunda nota do aluno: '))
print('A média de nota do aluno é {:.2f}'.format((nota1 + nota2) / 2))
print('\033[7m##########################################\033[m')
print('\033[7m##########################################\033[m')
