nome = input('Digite o seu nome completo: ')
print(nome.upper())
print(nome.lower())
print(len(nome), '- tamanho com espaços.')
print((len(nome) - (nome.count(' '))), '- tamanho sem espaços')
print(nome.split())
